# Generated by Django 5.0.4 on 2024-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will getall permissions granted to each of their groups.', related_name='user_customers', to='auth.group', verbose_name='groups'),
        ),
    ]
