# Generated by Django 5.0.4 on 2024-04-26 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number can only contain digits (0-9) and symbols (*+#-).', regex='^[0-9*+#-]+$')]),
        ),
    ]
