# Generated by Django 5.0.4 on 2024-05-23 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=9, validators=[django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
