# Generated by Django 5.0.4 on 2024-05-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_unit_name_alter_unit_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
